insert into Teacher values ('André Luís dos Reis Gomes de Carvalho', 'andre@cotuca.unicamp.br')
insert into Teacher values ('Andréia Cristina de Souza', 'andreia@cotuca.unicamp.br')
insert into Teacher values ('Francisco da Fonseca Rodrigues', 'chico@cotuca.unicamp.br')
insert into Teacher values ('Márcia Maria Tognetti Corrêa', 'marcia@cotuca.unicamp.br')
insert into Teacher values ('Patrícia Gagliardo de Campos', 'patricia@cotuca.unicamp.br')
insert into Teacher values ('Samuel Antônio de Oliveira', 'samuel@cotuca.unicamp.br')
insert into Teacher values ('Me. Sérgio Luiz Moral Marques', 'sergio@cotuca.unicamp.br')
insert into Teacher values ('Simone Pierini Facini Rocha', 'simone@cotuca.unicamp.br')