USE [BD16185]
GO

/****** Object:  Table [BD16185].[Student]    Script Date: 16/03/2018 09:13:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [BD16185].[Student](
	[RA] [int] NOT NULL,
	[Name] [varchar](30) NOT NULL,
	[Email] [varchar](30) NULL,
 CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
(
	[RA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

